apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: student-app-api
spec:
  hosts:
  - student-app-api
  http:
  - route:
    - destination:
        host: mongo
        port:
          number: 27017
